name: activeblendd
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using ⁠ flutter pub publish ⁠. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.15.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/google_logo.png
    - lib/assets/abrigo.png
    - lib/assets/banner_ropa.png
    - lib/assets/camiseta.png
    - lib/assets/chaqueta.png
    - lib/assets/google_logo.png
    - lib/assets/gorra.png
    - lib/assets/mochila.png
    - lib/assets/pantalon.png
    - lib/assets/sudadera.png
    - lib/assets/zapatillas.png
    - lib/assets/logo_alimentacion.png
    - lib/assets/logo_ropa.png
    - lib/assets/logo_material.png