// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxuj5rlhLXCu7X2l_GVFKbQxF-uF64zr0',
    appId: '1:43143766085:web:e06823cc1c703b85d8432c',
    messagingSenderId: '43143766085',
    projectId: 'activeblendd',
    authDomain: 'activeblendd.firebaseapp.com',
    databaseURL: 'https://activeblendd-default-rtdb.firebaseio.com',
    storageBucket: 'activeblendd.firebasestorage.app',
    measurementId: 'G-4CHFZRPQ28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg1rOTY6TsHikW0-2iIA8VZ1ukVx61Wc',
    appId: '1:43143766085:android:3ea3345f6327406ad8432c',
    messagingSenderId: '43143766085',
    projectId: 'activeblendd',
    databaseURL: 'https://activeblendd-default-rtdb.firebaseio.com',
    storageBucket: 'activeblendd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaomt3_ohkeyf58kvD_yY05HBpd59kw4U',
    appId: '1:43143766085:ios:40c686f0c7fda33ed8432c',
    messagingSenderId: '43143766085',
    projectId: 'activeblendd',
    databaseURL: 'https://activeblendd-default-rtdb.firebaseio.com',
    storageBucket: 'activeblendd.firebasestorage.app',
    iosBundleId: 'com.example.activeblendd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaomt3_ohkeyf58kvD_yY05HBpd59kw4U',
    appId: '1:43143766085:ios:40c686f0c7fda33ed8432c',
    messagingSenderId: '43143766085',
    projectId: 'activeblendd',
    databaseURL: 'https://activeblendd-default-rtdb.firebaseio.com',
    storageBucket: 'activeblendd.firebasestorage.app',
    iosBundleId: 'com.example.activeblendd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxuj5rlhLXCu7X2l_GVFKbQxF-uF64zr0',
    appId: '1:43143766085:web:64e1bf1a22009c4fd8432c',
    messagingSenderId: '43143766085',
    projectId: 'activeblendd',
    authDomain: 'activeblendd.firebaseapp.com',
    databaseURL: 'https://activeblendd-default-rtdb.firebaseio.com',
    storageBucket: 'activeblendd.firebasestorage.app',
    measurementId: 'G-09PHB4KVL6',
  );
}
